import Script from 'next/script';
import '../styles/globals.css';
import CompetitionListServer from '../components/CompetitionListServer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link 
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" 
            rel="stylesheet" 
            integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" 
            crossOrigin="anonymous">
        </link>
        <script src="https://kit.fontawesome.com/0cb4a876e8.js" crossOrigin="anonymous"></script>
      </head>
      <body>
        <nav className="top-navbar navbar navbar-expand-lg">
          <div className="container-fluid">
            <a className="navbar-brand" href="/">Score Board</a>
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarSupportedContent">
              <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                {/* <li className="nav-item">
                  <a className="nav-link" aria-current="page" href="/matches?status=ongoing">Live Matches</a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#">Link</a>
                </li> */}
              </ul>
            </div>
          </div>
        </nav>
        <div className="d-flex">
          <ul className="side-navbar nav nav-underline flex-column p-3 min-vh-100" data-bs-theme="light">
            <CompetitionListServer />
          </ul>
          <div className="flex-grow-1">
            {children}
          </div>
        </div>
        <Script 
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </body>
    </html>
  )
}

