import '../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link 
            rel="stylesheet" 
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ775/..."
            crossOrigin="anonymous" 
        />
        <script src="https://kit.fontawesome.com/0cb4a876e8.js" crossOrigin="anonymous"></script>
      </head>
      <body>{children}</body>
    </html>
  )
}

